name: Build and Deploy

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/xenontinkerer/libxenon:latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Login to GitHub Container Registry
      run: echo ${{ secrets.GHCR_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
    - name: Export variables
      run: |
        echo DEVKITXENON=/usr/local/xenon >> $GITHUB_ENV
        echo /usr/local/xenon/bin >> $GITHUB_PATH
        echo /usr/local/xenon/usr/bin >> $GITHUB_PATH
    - name: Build
      run: make
    - name: Build (dist)
      run: make dist
    - uses: actions/upload-artifact@v4
      with:
        name: XeLL-binaries
        path: XeLL_Reloaded-2stages-*.tar.gz
