name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: npmaile/libxenon-builder:latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Export variables
      run: |
        echo DEVKITXENON=/usr/local/xenon >> $GITHUB_ENV
        echo /usr/local/xenon/bin >> $GITHUB_PATH
        echo /usr/local/xenon/usr/bin >> $GITHUB_PATH
    - name: Build
      run: make
    - name: Build (dist)
      run: make dist
    - uses: actions/upload-artifact@v4
      with:
        name: XeLL-binaries
        path: XeLL_Reloaded-2stages-*.tar.gz
