name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/xenontinkerer/libxenon:latest  # Your custom container with libxenon

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          flex \
          bison \
          gcc-multilib \
          libgmp3-dev \
          libmpfr-dev \
          libmpc-dev \
          texinfo \
          git-core \
          build-essential \
          wget \
          file

    - name: Export variables
      run: |
        echo DEVKITXENON=/usr/local/xenon >> $GITHUB_ENV
        echo $DEVKITXENON/bin >> $GITHUB_PATH
        echo $DEVKITXENON/usr/bin >> $GITHUB_PATH

    - name: Build libxenon
      run: |
        git clone https://github.com/xenontinkerer/libxenon.git ../libxenon
        cd ../libxenon
        ./build-xenon-toolchain toolchain
        ./build-xenon-toolchain libxenon
        ./build-xenon-toolchain libs

    - name: Build XeLL
      run: |
        cd /app
        make

    - name: Build (dist)
      run: |
        cd /app
        make dist

    - uses: actions/upload-artifact@v4
      with:
        name: XeLL-binaries
        path: XeLL_Reloaded-2stages-*.tar.gz
