name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential git libtool autoconf automake texinfo libgmp-dev libmpfr-dev libmpc-dev flex bison

    - name: Clone and build libxenon
      run: |
        git clone https://github.com/xenontinkerer/libxenon.git ../libxenon
        cd ../libxenon
        ./autogen.sh
        ./configure --prefix=/usr/local/xenon
        make -j$(nproc)
        sudo make install

    - name: Export toolchain path
      run: |
        echo DEVKITXENON=/usr/local/xenon >> $GITHUB_ENV
        echo /usr/local/xenon/bin >> $GITHUB_PATH
        echo /usr/local/xenon/usr/bin >> $GITHUB_PATH

    - name: Build XeLL
      run: make

    - name: Build (dist)
      run: make dist

    - uses: actions/upload-artifact@v4
      with:
        name: XeLL-binaries
        path: XeLL_Reloaded-2stages-*.tar.gz
