static char* asciiart = "\n"
"With thanks to the XeLL authors, Octal450, ThisIsCheez, Xbox360Hub and everyone else involved.\n"
"\n"
"Thank you for purchasing a console from us! Visit: discord.gg/fab39r5x6M for support.\n"
"\n"
"\n"
" * Your console is running:\n"
"\n"
"\n"
"ÛÛ»  ÛÛ»ÛÛÛÛÛÛÛ»ÛÛ»     ÛÛ»         ÛÛÛÛÛÛ» ÛÛÛÛÛÛÛ»ÛÛ»      ÛÛÛÛÛÛ»  ÛÛÛÛÛ» ÛÛÛÛÛÛ» ÛÛÛÛÛÛÛ»ÛÛÛÛÛÛ» \n"
"ÈÛÛ»ÛÛÉ¼ÛÛÉÍÍÍÍ¼ÛÛº     ÛÛº         ÛÛÉÍÍÛÛ»ÛÛÉÍÍÍÍ¼ÛÛº     ÛÛÉÍÍÍÛÛ»ÛÛÉÍÍÛÛ»ÛÛÉÍÍÛÛ»ÛÛÉÍÍÍÍ¼ÛÛÉÍÍÛÛ»\n"
" ÈÛÛÛÉ¼ ÛÛÛÛÛ»  ÛÛº     ÛÛº         ÛÛÛÛÛÛÉ¼ÛÛÛÛÛ»  ÛÛº     ÛÛº   ÛÛºÛÛÛÛÛÛÛºÛÛº  ÛÛºÛÛÛÛÛ»  ÛÛº  ÛÛº\n"
" ÛÛÉÛÛ» ÛÛÉÍÍ¼  ÛÛº     ÛÛº         ÛÛÉÍÍÛÛ»ÛÛÉÍÍ¼  ÛÛº     ÛÛº   ÛÛºÛÛÉÍÍÛÛºÛÛº  ÛÛºÛÛÉÍÍ¼  ÛÛº  ÛÛº\n"
"ÛÛÉ¼ ÛÛ»ÛÛÛÛÛÛÛ»ÛÛÛÛÛÛÛ»ÛÛÛÛÛÛÛ»    ÛÛº  ÛÛºÛÛÛÛÛÛÛ»ÛÛÛÛÛÛÛ»ÈÛÛÛÛÛÛÉ¼ÛÛº  ÛÛºÛÛÛÛÛÛÉ¼ÛÛÛÛÛÛÛ»ÛÛÛÛÛÛÉ¼\n"
"ÈÍ¼  ÈÍ¼ÈÍÍÍÍÍÍ¼ÈÍÍÍÍÍÍ¼ÈÍÍÍÍÍÍ¼    ÈÍ¼  ÈÍ¼ÈÍÍÍÍÍÍ¼ÈÍÍÍÍÍÍ¼ ÈÍÍÍÍÍ¼ ÈÍ¼  ÈÍ¼ÈÍÍÍÍÍ¼ ÈÍÍÍÍÍÍ¼ÈÍÍÍÍÍ¼ \n"
"\n"
"\n"
"                                                                       ... courtesy of ZephyrWorksUK\n"
"\n\n";
static char* asciitail =
"Free60.org XeLL RELOADED - Xenon Linux Loader\n\n";
